version: "3.9"

services:
  web:
    build: .
    command: python /trendasemble/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/trendasemble
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-ua1t(!!f+qe#t+l@&kxv4++&6a6&+gci@z+wbyovp&-c^4ocgj"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: