# Generated by Django 4.0.8 on 2022-11-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.CharField(default='NA', max_length=200, primary_key=True, serialize=False)),
                ('album', models.CharField(max_length=500)),
                ('authorName', models.CharField(max_length=300)),
                ('coverLarge', models.CharField(max_length=500)),
                ('coverMedium', models.CharField(max_length=500)),
                ('coverThumb', models.CharField(max_length=500)),
                ('duration', models.IntegerField()),
                ('playUrl', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
    ]
