# Generated by Django 4.0.8 on 2022-11-27 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('music', models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, to='tiktok.music')),
            ],
        ),
    ]
