import Head from "next/head";
import Image from "next/image";
import InstaTrend from "../components/instaTrend";
import SideNav from "../components/sideNav";
import Nav from "../components/Nav";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import TwitterTrend from "../components/twitterTrend";
import TiktokTrend from "../components/tiktokTrend";
import GoogleTrend from "../components/googleTrends";

interface PTypes {
  click:() => string;
  change: string;
}

export default function Home() {
  const [change, setChange] = useState("1");

  const click: any = (e: any) => {
    setChange(e.target.id);
  };
  console.log(click.value)


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Nav />
        <div className={styles.home}>
          <SideNav click={click} change={change} />

          {change === "2" ? (
            <TwitterTrend />
          ) : change === "3" ? (
            <TiktokTrend />
          ) : change === "4" ? (
            <GoogleTrend />
          ) : (
            <InstaTrend />
          )}

          {/* <InstaTrend /> */}
        </div>
      </main>
    </div>
  );
}
